# Generated by Django 4.2.7 on 2023-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('trailer_url', models.URLField()),
                ('timings', models.DateTimeField()),
                ('artists', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
