# Generated by Django 4.2.7 on 2023-12-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_concert_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
