# Generated by Django 4.2.7 on 2023-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_concert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('num_of_people', models.IntegerField()),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('card_expiry', models.CharField(max_length=4, verbose_name='Card Expiry')),
                ('card_cvc', models.CharField(max_length=3, verbose_name='Card CVC')),
                ('card_name', models.CharField(max_length=255, verbose_name='Card Holder Name')),
            ],
        ),
    ]
