# Generated by Django 4.2.7 on 2023-12-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_booking_concert_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
